version: '3.4'

services:

  nginx_server_proxy:    
    build: ./nginx/    
    container_name: nginx_server_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gateway
    depends_on:
      - api_gateway

  api_gateway:
    build: ./rust_api_gateway/
    container_name: api_gateway
    ports:
      - "8080:8080"
    networks:
      - gateway
    links: # This should make visible to other applications
      - cars_api
      - users_api
    
  cars_api:
    build: ./bun_cars/
    container_name: cars_api
    ports:
      - "8001:8001"
    networks:
      - gateway
    # depends_on:
    #   - nginx_proxy

  users_api:
    build: ./python_users/
    container_name: users_api
    ports:
      - "8000:8000"
    networks:
      - gateway
    # depends_on:
    #   - nginx_proxy

networks:
  gateway:
    driver: bridge

